apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-cicd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-cicd
    spec:
      containers:
      - name: hello-cicd
        image: IMAGEPATH:TAG
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: hello-cicd
